### ISSUE TITLE
Non-Billable hours showing up as billable in reports

### ISSUE THREAD

**Issue by matthiasdeboer** [FrontMen/fm-hours#154] opened 2021-07-08 11:15 UTC
User Ye Jun Wu has booked all his hours in June as Available (non-billable). However in the report overview all his hours are showing up as billable

**Comment by vladPinteaFrontmen** [comment] 2021-07-16 09:13
In prod, the records are saved with isBillable: true, so the UI is working as intended. 

The reason why they were marked as billable is unclear. 
I have tried mixing and matching billable and not billable projects to try to get the same result but could not reproduce in dev. 

There is a possibility that the project was incorrectly marked as billable at the time the sheets were submitted. If a customer is changed from billable to not billable, past sheet are not updated, as would be normal in most cases.

**Comment by sanderdejong88** [comment] 2021-07-27 08:44
@matthiasdeboer what do you think?

**Closed** 2021-07-27 09:14 UTC
